version: '3.8'
networks:
  akuntansi:
services:
  nginx_akuntansi:
    image: nginx:alpine
    container_name: nginx_akuntansi
    ports:
      - '8038:8038'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - akuntansi
      - akuntansi_db
    networks:
      - akuntansi
  akuntansi_db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'akuntansi'
      MYSQL_USER: 'dimas'
      MYSQL_PASSWORD: 'dimas1950'
      MYSQL_ROOT_PASSWORD: 'dimas1950'
    ports:
      - '3308:3306'
    networks:
      - akuntansi

  akuntansi:
    container_name: akuntansi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - primary_simrs
